# Generated by Django 2.2.28 on 2022-04-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220412_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='verification_period',
            field=models.CharField(choices=[('One Week', 'One Week'), ('Two Week', 'Two Week'), ('One Month', 'One Month')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Category'),
        ),
    ]
