# Generated by Django 2.2.28 on 2022-04-26 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220419_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuthentication',
            fields=[
                ('emailtokenverification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.EmailTokenVerification')),
            ],
            bases=('users.emailtokenverification',),
        ),
        migrations.AddField(
            model_name='user',
            name='buddy',
            field=models.ManyToManyField(blank=True, related_name='users_buddy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='storage',
            field=models.FloatField(default=100),
        ),
    ]
