# Generated by Django 2.2.28 on 2022-04-26 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220426_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddy',
            name='user',
        ),
        migrations.AddField(
            model_name='buddy',
            name='buddy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buddy_buddy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buddyinvitation',
            name='relationship',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='buddy',
            field=models.ManyToManyField(to='users.Buddy'),
        ),
    ]
