# Generated by Django 2.2.28 on 2022-06-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220426_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_left',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='buddy',
            field=models.ManyToManyField(blank=True, to='users.Buddy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
