# Generated by Django 2.2.28 on 2022-06-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220608_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_2FA',
            field=models.BooleanField(default=True),
        ),
    ]
