# Generated by Django 2.2.28 on 2022-10-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220620_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_payment_method',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
