# Generated by Django 2.2.28 on 2022-12-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20221114_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
    ]
