# Generated by Django 2.2.28 on 2022-11-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20221118_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulenotification',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '----'), (1, 'Prime'), (2, 'Buddy')], default=0),
        ),
    ]
