# Generated by Django 2.2.28 on 2022-11-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20221116_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
