# Generated by Django 2.2.28 on 2022-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_folders', '0002_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
